### ISSUE TITLE
Upload files hyperlink

### ISSUE THREAD

**Issue by thelastinuit** [fly-apps/live_beats#26]
The drag and drop works perfectly, however, clicking the hyperlink does not pop up the window to select files.

Browser: Firefox 96.0.3 (64-bit) mac

![Screen Shot 2022-02-02 at 8 17 50](https://user-images.githubusercontent.com/944683/152171379-bdac1bdb-8d94-402f-b885-450c2624f1bb.png)

![Feb-02-2022 08-18-11](https://user-images.githubusercontent.com/944683/152171417-1f83e951-ff5c-4d48-afe3-5ef59a9d0590.gif)

**Comment by Allyedge** [comment]
It doesn't work on Windows 11 + Google Chrome either.
