### ISSUE TITLE
Cannot upload MP3 without ID3 tags

### ISSUE THREAD

**Issue by colinstark** [fly-apps/live_beats#29]
Hello 👋
Tried uploading an MP3 (17.6mb) that I converted from WAV with Firefox 96.0.3 on macOS, it stopped in the middle of the upload process:

<img width="633" alt="no-valid-mp3" src="https://user-images.githubusercontent.com/5658185/152229489-a7b597d5-c23a-4218-abad-7c4a4818f324.png">

after adding ID3 for artist & title and re-exporting, it worked. Is checking for valid ID3 tags part of the upload validation check? If so, can the app display _what_ is wrong with the file?

**Comment by chrismccord** [comment]
We don't necessary require the ID3 tags, but our parser may not be taking into account some encodings. If you're able, you could try running locally and see what either of these clauses get angry about https://github.com/fly-apps/live_beats/blob/master/lib/live_beats/mp3_stat.ex#L57-L61

**Comment by colinstark** [comment]
fixed in https://github.com/fly-apps/live_beats/pull/44 :)
