### ISSUE TITLE
Integrate LiveBeats with Discord Presence

### ISSUE THREAD

**Issue by bl0cknumber** [fly-apps/live_beats#32]
Friends can join by click join button in your discord status then go to your profile link.

**Comment by bolshoytoster** [comment]
@bl0cknumber [this](https://hexdocs.pm/discord_ex/DiscordEx.Client.html#status_update/2) might be helpful if you don't mind adding a dependency. It only you set status though, not presence/activity.

**Comment by bl0cknumber** [comment]
> @bl0cknumber [this](https://hexdocs.pm/discord_ex/DiscordEx.Client.html#status_update/2) might be helpful if you don't mind adding a dependency. It only you set status though, not presence/activity.

I see, interesting, i will modify this issue.

**Comment by chrismccord** [comment]
We aren't taking feature requests, but forking this and adding a blog post about how you added it would be great community content :)
