### ISSUE TITLE
Failed sign out on brave browser

### ISSUE THREAD

**Issue by relax2code** [fly-apps/live_beats#41]
Hi,  first I'm really thank you for making this full example
it's really helpful to understand phoenix live view .
I have a question  the sign out doesn't work for brave browser with error:

This page isn’t workingIf the problem continues, contact the site owner.
HTTP ERROR 431

I've tried in chrome and firefox browser and it works, is there any additional settings  I should add for brave browser case ?
Thank you

**Comment by chrismccord** [comment]
Works just fine for me, 431 is `431 Request Header Fields Too Large`, which is weird because the only thing we store in the cookie session is the user ID, so perhaps it's something on your side. Let me know if you can provide more information. Thanks!

**Comment by relax2code** [comment]
Thanks , and yes the problem is my brave browser has many cookies for http://localhost:4000 site,
it works after I cleaned up the cookies
Thank you very much
