### ISSUE TITLE
Non Liveview Page

### ISSUE THREAD

**Issue by joshchernoff** [fly-apps/live_beats#46]
When reviewing the router it does not look as if the PageController gets used. 
I was trying to review what non live view pages this app was using to see how they incorporate them, from what I can tell its not used at all. 

Not sure if I'm just overlooking something, but it would seem there is no reason to keep the listed files. 
* lib/live_beats_web/controllers/page_controller.ex
* lib/live_beats_web/templates/page/index.html.heex
* lib/live_beats_web/views/page_view.ex
* test/live_beats_web/views/page_view_test.exs

**Comment by chrismccord** [comment]
Agree, they can be killed :) The only controllers are the OAuthController, and  FileController. Thanks!
