### ISSUE TITLE
Unable to sign in with github

### ISSUE THREAD

**Issue by sodapopcan** [fly-apps/live_beats#57]
I recently changed my email address so this may have something to do with it, but any time I try and sign in, I get "We were unable to fetch the necessary information from your Github account".  I tried signing in fresh with cleared cookies and whatnot to no avail.  I still have my old email listed in github, it's just not my primary one (although I'm not sure if that has anything to do with it).

**My info**
- Firefox 106.0.3
- macOS Ventura 13.0, MacBook Air, M1 2020

**Comment by lszyba1** [comment]
hmm,.
I just signup, and it worked. 
try private browsing? 
make sure you are logged on from GH.
