### ISSUE TITLE
A few UI bugs

### ISSUE THREAD

**Issue by hubertlepicki** [fly-apps/live_beats#58]
Hey, first of all *great demo*, I love it!

Having said that, I may have found a few bugs in the version deployed to https://livebeats.fly.dev. Attaching a video below. 

Summary:

1. You can start/stop playing on your own profile even if you have no songs - this appears to do nothing. (time: 0:00:5)
2. I cannot play own or other people's songs by clicking on title (0:00:13)
3. "Play" button on people's profiles does nothing (0:00:28)
4. Player gets confused on what it's playing - appears to be playing @chrismccord song while on my own profile (0:01:00)
5. Playing own song by clicking on title doesn't work, while the icon changes to playing, no song actually plays, icon seems stuc in playing state (0:01:28)

Hope it's helpful and maybe someone wants to get rif of these / improve UI!

https://user-images.githubusercontent.com/33274/209812499-82549920-7f54-4e35-981a-12c3d0fdb76b.mp4

**Comment by josevalim** [comment]
We should be all good, feel free to report if anything else.
