### ISSUE TITLE
An .svg link returns a 404

### ISSUE THREAD

**Issue by gregmsanderson** [fly-apps/live_beats#63]
Hi,

The app builds a URL to an .svg like `https://fly.io/ui/images/#{@region}.svg`.

However that link currently returns a 404 and results in a broken image icon next to the ping time. For example `https://fly.io/ui/images/lhr.svg` and `https://fly.io/ui/images/iad.svg`. Both return a 404, at least for me. I'm not sure if that .svg has since been moved elsewhere or is only available for particular regions.

**Comment by chrismccord** [comment]
Fixed thanks!
