### ISSUE TITLE
Hitting "Cancel" on upload song modal, re-opening and hitting "Save" crashes the app displaying "Re-establishing connection" forever

### ISSUE THREAD

**Issue by hubertlepicki** [fly-apps/live_beats#72]
If you start uploading a song, then "Cancel" in the middle, and then if you re-open the modal

1. The modal is now in some undefined state, having a progress bar from previous upload
2. You can hit "Save" button, which now breaks something further and "Re-establishing connection" is now forever visible

As a side note, you should probably also not be able to click "Save" while the file is uploading.

https://github.com/fly-apps/live_beats/assets/33274/1164f399-095e-4504-8677-700d416684ec

**Comment by hubertlepicki** [comment]
As a side note, I think something should happen when the upload finishes and progress bar reaches 100%. As it is now, it stays there at 100% without giving user any indication that they can now safely hit "Save'

**Comment by sabit990928** [comment]
Adding loading bar on button when you click save would be good as well.

**Comment by chrismccord** [comment]
This was a bug on LV main. Thanks!
